apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bsa8xfkol-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bsa8xfkol-dotnet-basic-gitops